name: Cleanup PR Deployment

on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: write

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          role-session-name: GitHubActions-Cleanup-PR-${{ github.event.number }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Cleanup S3 deployment
        run: |
          PR_FOLDER="pr-${{ github.event.number }}"
          echo "Cleaning up deployment for PR #${{ github.event.number }}"
          aws s3 rm s3://${{ vars.S3_BUCKET_NAME }}/$PR_FOLDER/ --recursive

      - name: Update PR comment
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = context.payload.number;

            try {
              // Find existing deployment comment
              const comments = await github.rest.issues.listComments({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber,
              });

              const botComment = comments.data.find(comment =>
                comment.user.type === 'Bot' &&
                comment.body.includes('🚀 **PR Deployment**')
              );

              if (botComment) {
                const commentBody = `🚀 **PR Deployment**

                ~~Your changes were deployed and are now cleaned up.~~

                **Status:** ✅ Deployment cleaned up after PR closure.

                _This comment was automatically updated._`;

                await github.rest.issues.updateComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  comment_id: botComment.id,
                  body: commentBody
                });

                console.log('Updated deployment comment for PR #' + prNumber);
              } else {
                console.log('No deployment comment found for PR #' + prNumber);
              }
            } catch (error) {
              console.error('Error updating comment:', error);
            }
